CREATE DATABASE wildlife_tracker;

\c wildlife_tracker;
CREATE TABLE  sightings(
    sightingId int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rangerName VARCHAR,
    endangeredAnimal BOOLEAN,
    LOCATION VARCHAR
);

CREATE DATABASE wildlife_tracker_test WITH TEMPLATE wildlife_tracker;